### ISSUE TITLE
ddclient conf example

### ISSUE THREAD

**Issue by sephallen** [digitalm3/DigitalOcean_dyndns#1]
Hi, I really appreciate all the great work you've done on this project!
I have everything installed on my server and my next step is to set up ddclient on my machine, but this is where I am not sure how to proceed.

Do you have an example conf file I could reference?

Thanks for all your hard work!

**Comment by digitalm3** [comment]
The client I use is built into my firewall and I don't have access to the config but this is an example i downloaded:

protocol=dyndns2
use=web
server=dyn.domain.com     #server hosting the DigitalOcean_dyndns
login='{login}'     #setup in htpassword
password='{password}'     #setup in htpassword
sever.domain.com     #DNS record you want to update.

The login and password would be the username and password you setup in apache or nginx for the DigitalOcean_dyndns site.  For me I used htpassword and I use my domain name for the login and then a strong password.

**Comment by sephallen** [comment]
Great, thanks again for everything!

**Comment by digitalm3** [comment]
sure thing, i'm glad you find it useful, please let me know if you run into any troubles :)
